# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# configure dependency pinning globally
# default: True
# allowed: True, False
pin: True

# set the default branch
# default: empty, the default branch on GitHub
branch: development

# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule: "every day"

# search for requirement files
# default: True
# allowed: True, False
search: True


# assign users to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
assignees:
 - isaacsquires

# configure the branch prefix the bot is using
# default: pyup-
branch_prefix: pyup/

# allow to close stale PRs
# default: True
close_prs: True